# Project Name
TARGET = 4_voice_synth

# Sources
CPP_SOURCES = 4_voice_synth.cpp

# Library Locations
LIBDAISY_DIR = C:/Users/jason/Documents/DaisyExamples/libdaisy
DAISYSP_DIR = C:/Users/jason/Documents/DaisyExamples/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

